### ISSUE TITLE
Forking and changing the footer

### ISSUE THREAD

**Issue by pan100** [mannynotfound/react-tweet#16]
I assume there is no problem in making a fork of this and adding a new icon to the footer? I am making a Twitter app where I need a new icon in the footer.

Could you please explain what the 4th div in the Footer.js render is doing? Is it a placeholder? Can I just add something here or does it do something in rare cases? In the example app it is empty.

This one:

`          <div className="ProfileTweet-action" style={styles.ProfileTweetAction}>
            <button className="ProfileTweet-actionButton" style={styles.ProfileTweetActionBtn}>
              <div className="IconContainer" style={styles.IconContainer}>
                <span className="Icon Icon--more" style={styles.Icon} />
              </div>
            </button>
          </div> `

**Comment by mannynotfound** [comment]
What icon do you want to add to the footer? If its custom to your app I would say make a fork, but if its inline with latest twitter I would be open to a pull request. 

That div is indeed a placeholder, its the icon that houses the "dm" button but since I knew I wasnt going to support DMing in this component, I left it out. The whole footer is static really.
